#!/bin/sh
set -e
echo ""
echo "Executing sorting algorithms."
read -n 1 -s -r -p "Press any key to begin."
echo ""
echo "************************************"
echo "Insertion sort                     *"
echo "************************************"
python3 insertion_sort.py
echo ""
read -n 1 -s -r -p "Press any key to continue."
echo ""
echo "************************************"
echo "Merge sort                         *"
echo "************************************"
python3 merge_sort.py
echo ""
read -n 1 -s -r -p "Press any key to continue."
echo ""
echo "************************************"
echo "Quicksort                          *"
echo "************************************"
python3 quicksort/quicksort.py
echo ""
read -n 1 -s -r -p "Press any key to continue."
echo ""
echo "************************************"
echo "Heapsort                           *"
echo "************************************"
python3 heapsort/heapsort.py
echo ""
read -n 1 -s -r -p "Press any key to continue."
echo ""
echo "************************************"
echo "Counting sort                      *"
echo "************************************"
python3 linear_time_sorting/counting_sort.py
echo ""
read -n 1 -s -r -p "Press any key to continue."
echo ""
echo "************************************"
echo "Radix sort                         *"
echo "************************************"
python3 linear_time_sorting/radix_sort.py
echo ""
read -n 1 -s -r -p "Press any key to continue."
echo ""
echo "************************************"
echo "Bucket sort                        *"
echo "************************************"
python3 linear_time_sorting/bucket_sort.py
echo ""
echo ""
echo "Done."
